addfriend/urls.py
from django.conf.urls import url
from .views import index, add_friend
urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_friend', add_friend, name='add_friend')
]

profile/urls.py
from django.conf.urls import url
from .views import profile
#url for app
urlpatterns = [
    url(r'^$', profile, name='profile'),
]

stats/urls.py
from django.conf.urls import url
from .views import stats
#url for app
urlpatterns = [
    url(r'^$', stats, name='stats'),
]

tp1ppw/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
import updatestatus.urls as updatestatus
import addfriend.urls as addfriend
import profile.urls as profile
import stats.urls as stats
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^updatestatus/', include(updatestatus,namespace='updatestatus')),
    url(r'^$', RedirectView.as_view(url='updatestatus/', permanent=True), name='$  '),
	url(r'^addfriend/', include(addfriend,namespace='addfriend')),
    url(r'^profile/', include(profile,namespace='profile')),
	url(r'^stats/',include(stats,namespace='stats')),
]

updatestatus/urls.py
from django.conf.urls import url
from .views import index, add_status, delete_status

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', add_status, name='add_status'),
    url(r'^delete_status/(?P<id_status>\d+)/$', delete_status, name = 'delete_status'),
]

addfriend/models.py
from django.db import models

# Create your models here.
class AddFriend(models.Model):
	name = models.CharField(max_length=40)
	link = models.URLField(max_length=40)
	created_date = models.DateTimeField(auto_now_add=True)

profile/models.py
from django.db import models

# Create your models here.
class ProfileData(models.Model):
	name = models.CharField(max_length=250)
	Birthday = models.CharField(max_length=20)
	Gender = models.CharField(max_length=200)
	expertise = models.TextField(max_length=200)
	Description = models.CharField(max_length=200)
	Email = models.CharField(max_length=200)

stats/models.py
from django.db import models

# Create your models here.

updatestatus/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
	title = models.CharField(max_length=27)
	description = models.TextField()
	created_date = models.DateTimeField(auto_now_add=True)

addfriend/forms.py
from django import forms

class AddFriend_Form(forms.Form):
	error_messages = {
        'required': 'This field is required.',
    }
	name_attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder':'Masukan nama...'
    }
	link_attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder':'Masukan link, contoh : https://kelompok5C.herokuapp.com'
    }
	name = forms.CharField(label='Nama ', required=True, max_length=40, widget=forms.TextInput(attrs=name_attrs),error_messages = error_messages)
	link = forms.URLField(label='URL  ', required=True, max_length=40, widget=forms.TextInput(attrs=link_attrs),error_messages = error_messages)

updatestatus/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Please write your input here',
    }
    
    description_attrs = {
        'type': 'text',
        'cols': 90,
        'rows': 4,
        'class': 'status-form-textarea',
        'placeholder':"Type in your status here...",
    }

    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

class Comment_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }

    description_attrs ={
        'type': 'text',
        'cols': 60,
        'rows': 10,
        'class': 'comment-form-textarea',
        'placeholder':' Write your comment here. . '
    }
    comment = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

addfriend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import AddFriend
from .forms import AddFriend_Form

# Create your views here.
response = {}

def index(request):
    response['author'] = "Kelompok 5C"
    addfriend = AddFriend.objects.all()
    response['addfriend'] = addfriend
    html = 'addfriend/addfriend.html'
    response['addfriend_form'] = AddFriend_Form
    response['app'] = 'Add Friend'
    return render(request, html, response)
    
def add_friend(request):
    addfriend = AddFriend_Form(request.POST or None)
    if(request.method == 'POST' and addfriend.is_valid()):
        response['name'] = request.POST['name']
        response['link'] = request.POST['link']
        addfriendd = AddFriend(name=response['name'],link=response['link'])
        addfriendd.save()
        return HttpResponseRedirect('/addfriend/')
    else:
        return HttpResponseRedirect('/addfriend/')

profile/views.py
from django.shortcuts import render
from datetime import datetime, date
from .models import ProfileData

author = 'Kelompok 5C'
name = 'Hepzibah Smith' #TODO implement your name here
birth_date = date(1995,4,23) #TODO implement your birthday
birthdate = birth_date.strftime('%d %B %Y')
gender = 'Male' #TODO implement your gender
email = 'hello@smith.com' #TODO implement your email
desc_profile = "Full Stack Developer"
#TODO implement your expertise minimal 3
expert = ["Back End", "Front End", "UI/UX"]

def profile(request):
	# response = {}
	# response['author'] = "Kelompok 5C"
	# response = {'prof_dict': prof_dict}
	# return render(request, 'profile.html', response)
	profil = ProfileData(name = name, Birthday = birthdate, Gender= gender, Email = email, Description=desc_profile, expertise=expert)
	response = {'name' : profil.name, 'Birthday' : profil.Birthday, 'Gender': profil.Gender, 'Expertise': profil.expertise, 
	'Description' : profil.Description, 'Email': profil.Email, 'author':author,'app':'Profile'}
	html = 'profile.html'
	return render(request, html, response)

stats/views.py
from django.shortcuts import render
from addfriend.models import AddFriend
from updatestatus.models import Status
from profile.views import name

# Create your views here.
def stats(request):
    status = Status.objects.all()
    feedCount = Status.objects.all().count()
    response = {'author':'Kelompok 5C','friendz':AddFriend.objects.all().count(),
                'feed':feedCount,'name':name, 'app':'Dashboard'};
    if(feedCount > 0):
        response['status'] = status[feedCount - 1]
    return render(request, 'stats.html', response)

updatestatus/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Status
from .forms import Status_Form
from profile.views import name

# Create your views here.
response = {}

def index(request):
    response['author'] = "Kelompok 5C"
    status = reversed(Status.objects.all())
    response['status'] = status
    html = 'updatestatus/updatestatus.html'
    response['status_form'] = Status_Form
    response['app'] = "Update Status"
    response['name'] = name
    return render(request, html, response)

def add_status(request):
    form = Status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['description'] = request.POST['description']
        status = Status(description=response['description'])
        status.save()
        return HttpResponseRedirect('/updatestatus/')
    else:
        return HttpResponseRedirect('/updatestatus/')

def delete_status(request, id_status):
    status = Status.objects.get(pk = id_status)
    status.delete()
    return HttpResponseRedirect('/updatestatus/')

addfriend/templates/addfriend/addfriend.html
{% extends "base.html" %}

{% block style %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/addfriend.css' %}" />
{% endblock %} 

{% block content %}
<section name="input-list" id = "input-list">
		<h1>Add Friends</h1>
        <form class = "form-horizontal" id="form" method="POST" action="{% url 'addfriend:add_friend' %}" style="width: 80%; margin-top: 30px;">
            {% csrf_token %}
            {% for datum in addfriend_form %}
			 <div class="container-fluid">
			  <label class="control-label col-sm-2" for="datum.name">{{datum.label}}:</label>
			  <div class="col-sm-10">
				{{datum}}
			  </div>
			</div>
			{% endfor %}
			<div id="submit-button" style = "padding: 10px 70px 10px 80px; width: 165%;" align = "center">
				<input id="submit" type="submit" class="butt btn btn-lg btn-info" value="Add Friend">
			</div>
        </form>
</section>
<section name="my-list" id="my-list">
    <div class="container">
        <h2 style = "text-align: center">Friends List</h2>
		<br/>
        <div class="flex">
            {% if addfriend %}
                {% for data in addfriend %}
                    <div class="flex-item">
                        <div class="to-do-list">
							<br/>
							<img style = "border-radius: 100%; width: 70px; height: 80px;" src="http://www.youthcoalition.org/wp-content/uploads/my_page_default_img-adfe835c1f5d2c834505fd2c411402ea63978141ec42bac99ddf712a1e692bdd.png"" style="width:304px;height:228px;">
						
                            <div class="to-do-list-name" style = "color:blue">
							<br/>
                                {{data.name}}
                            </div>
                            <div class="to-do-list-date-added" style = "color: green">
                                Added  {{data.created_date}}
                            </div>
                            <div class="to-do-list-description" style = "text-align:center;">
                                <a href = {{data.link}}>{{data.link}} </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada Teman.
            </div>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}

addfriend/templates/addfriend/addfriend1.html
{% extends "base.html" %}

{% block content %}
<h1 class="main-title">Add Friends</h1>
<hr/>
<section name="input-list" id = "input-list">
		<h2>Add Friends</h2>
        <form class = "form-horizonral" id="form" method="POST" action="{% url 'addfriend:add_friend' %}">
            {% csrf_token %}
            {% for datum in addfriend_form %}
			 <div class="container-fluid">
			  <label class="control-label col-sm-2" for="datum.name">{{datum.label}}:</label>
			  <div class="col-sm-10">
				{{datum}}
			  </div>
			</div>
			{% endfor %}
			<div style = "padding: 10px 35px 10px 45px;" align = "right">
				<input id="submit" type="submit" class="butt btn btn-md btn-info" value="Add Friend">
			</div>
        </form>
</section>
<section name="my-list" id="my-list">
    <div class="container">
        <h2 class="my-list-title">My List</h2>
        <div class="flex">
            {% if addfriend %}
                {% for data in addfriend %}
                    <div class="flex-item">
                        <div class="to-do-list">
                            <div class="to-do-list-name">
                                {{data.name}}
                            </div>
                            <div class="to-do-list-date-added">
                                Added  {{data.created_date}}
                            </div>
                            <div class="to-do-list-description">
                                <a href = {{data.link}}>{{data.link}} </a>
                            </div>
                             <!--<div class="to-do-list-delete-button" input id="sumbit" type="submit" data-id="{{data.id}}" value="Delete"></div>-->
							<form id="form-{{data.id}}" method="post" action="{% url 'lab-5:remove_todo' %}">
										{% csrf_token %}
								<input type="hidden" name="flag" value="{{data.id}}"/>
								<input id = "submit{{data.id}}" id="delete-{{data.id}}" type="submit" data-id="{{data.id}}" value="Delete" class="to-do-list-delete">
							</form>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada Teman.
            </div>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}

profile/templates/profile.html
{% extends "base.html" %}

{% block content %}
<h1>{{name}}'s Profile</h1>
<br>
<section id ="profile">
	<div class="container text-center">
		<div class="row">
			<div class="col-sm-8 col-sm-offset-2">
				<img class = "img-circle" src ="https://pbs.twimg.com/profile_images/824716853989744640/8Fcd0bji.jpg" width="200px" height="200px">
				<h2 align = "center" >{{ name }}</h2>

				<table align = "center" width="400" cellspacing = "20" cellpadding="40">
				<tr>
					<td align = "left">Birthday</td>
					<td align = "left">{{ Birthday }}</td>
				</tr>
				<tr>
					<td align = "left">Gender</td>
					<td align = "left">{{ Gender }}</td>
				</tr>
				<tr>
					<td align = "left">Expertise</td>
					<td> <table style="text-align: left">
							<td class="value">{% for ii in Expertise %}<div class = "row-xs-12"><span id="expert" class="expert">{{ii}}</span>{% endfor %}</div>
							</td>
						</table>
					</td>
				</tr>
				<tr>
					<td align = "left">Description</td>
					<td align = "left">{{  Description }}</td>
				</tr>
				<tr>
					<td align = "left">Email</td>
					<td align = "left">{{ Email }}</td>
				</tr> 
				</table>
			</div>
		</div>
	</div>
</section>
</br>

{% endblock %}

stats/templates/stats.html
{% extends "base.html" %}

{% block content %}
<style type="text/css">
	.image{
		border-radius:90%;
		width: 300px;
		height: 300px;
		margin:auto;
		display: block;
	}
	.feed{
		font-size:28px;
		text-align:center;
	}
	h1{
		margin-top: 50px;
		text-align: center;
	}
</style>
<h1>Statistics</h1>
<section name ="profile" style="margin-top: 25px">
	<img src="https://pbs.twimg.com/profile_images/824716853989744640/8Fcd0bji.jpg" class="image"	alt="My image"/>
	<p class = "feed"> {{name}}</p>
</section>

<p class = "feed"><strong>Friends: {{friendz}}</strong><p>
<p class = "feed"><strong>Feed: {{feed}}</strong><p>
<hr/>
<section name="latest" class="container" style="width:80%">
	<h2>Latest Post</h2>
	{% if status %}
		<div class="flex-item">
			<div class="status">
				<div class="status-description" style="color: blue">
					{{status.description}}
				</div>
				<div class="status-date-added">
					{{status.created_date}}
				</div>
			</div>
		</div>
	{% else %}
		<p>Tidak ada data Status.</p>
	{% endif%}
</section>
<hr/>
<hr/>
{% endblock %}

templates/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="TUGAS 1">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Catamaran" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Quicksand' rel='stylesheet'>
	{% block style %}
	
	{% endblock %}
    <title>
        {% block title %} LingIn | {{app}} {% endblock %}
    </title>
</head>
<style type="text/css">
    body {
        font-family: Quicksand;
    }
</style>
<body>
    <div class="head">
    <header>
        {% include "partials/header.html" %}
    </header>
    </div>
    <br><br><br>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        {% block footer %}
        {% include "partials/footer.html" %}
        {% endblock %}
    </footer>
    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>
</body>
</html>

templates/partials/footer.html
<p style="text-align: center;font-size: 15px;">&copy;Made by {{author}}</p>

templates/partials/header.html
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'profile:profile' %}" style="font-size: 20px;">LingIn</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse" style="float: right; font-size: 18px;">
      <ul class="nav navbar-nav">
        <!-- LINK MENUJU table, dan link menuju home#form -->
        <li><a href="{% url 'updatestatus:index' %}">Status</a></li>
        <li><a href="{% url 'profile:profile' %}">Profile</a> </li>
		    <li><a href="{% url 'addfriend:index' %}">Friends</a> </li>
		    <li><a href="{% url 'stats:stats' %}">Stats</a> </li>
      </ul>
    </div><!--/.nav-collapse -->
</nav>

updatestatus/templates/updatestatus/layout/base.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <meta name="description" content="Update Status">
    <meta name="author" content="Kelompok 5C">
    <!-- bootstrap css -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/updatestatus.css' %}" />

    <title>
        {% block title %} LingIn | Update Status {% endblock %}
    </title>
</head>
<style type="text/css">
    body {
        background: red; /* For browsers that do not support gradients */
        background: -webkit-linear-gradient(-90deg, #00a8c5, #ffff7e); /* For Safari 5.1 to 6.0 */
        background: -o-linear-gradient(-90deg, #00a8c5, #ffff7e); /* For Opera 11.1 to 12.0 */
        background: -moz-linear-gradient(-90deg, #00a8c5, #ffff7e); /* For Firefox 3.6 to 15 */
        background: linear-gradient(-90deg, #00a8c5, #ffff7e); /* Standard syntax */
    }
</style>
<body>
    <header>
        {% include "partials/header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
            <!-- content goes here -->
            {% endblock %}
        </div>
    </content>
    <footer>
        {% block footer %}
        {% include "partials/footer.html" %}
        {% endblock %}
    </footer>
    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

updatestatus/templates/updatestatus/updatestatus.html
{% extends "base.html" %}

{% block content %}
<br><br><br>
<section name="input-list" id="input-list">
    <div class="container">
        <form id="form" method="POST" action="{% url 'updatestatus:add_status' %}">
            <p name="status-tagline">What's on your mind?</p>
            {% csrf_token %}
            {{ status_form }}
            <br>
            <input id="submit" type="submit" class="btn btn-lg btn-info" value="Submit">
            <br>
        </form>
    </div>
</section>

<section name="my-list" id="my-list">
    <div class="container">
    <br><br>
        <div class="flex">
            {% if status %}
                {% for data in status %}
                    <div class="flex-item">
                        <div class="status">
                            <div class="prof-pic"><img src="https://pbs.twimg.com/profile_images/824716853989744640/8Fcd0bji.jpg" width="50px" height="50px" style="border-radius: 50%"></div>
                            <a href="/updatestatus/delete_status/{{ data.id }}" class="close" style="margin-top: -40px;margin-right: 10px">
                                <img src="http://www.clker.com/cliparts/0/7/e/a/12074327311562940906milker_X_icon.svg.hi.png" width="20px" height="20px"></img>
                            </a>
                            <div class="name" style="font-size: 20px">{{name}}</div>
                            <div class="status-description" style="font-size: 18px;margin-top: 10px">
                                {{data.description}}
                            </div>
                            <div class="status-date-added" style="color: grey">
                                {{data.created_date}}
                            </div>
                        </div>
                    </div>
                    <br>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada data Status.
            </div>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}